# Generated by Django 5.2.4 on 2025-08-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_post_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Unlike')], default='', max_length=7),
            preserve_default=False,
        ),
    ]
