# Generated by Django 5.2.4 on 2025-08-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_like_reaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='like',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('unlike', 'Unlike')], max_length=7),
        ),
    ]
